### ISSUE TITLE
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_10_R1/entity/CraftPlayer

### ISSUE THREAD

**Issue by PsychoLynx** [TealNerd/RadarJammer#7]
RadarJammer b#38, Spigot 1.11 (git-Spigot-f950f8e-ad0e4b) (built today).

On login and continuously, several times a second this error appears:
[14:31:49] [User Authenticator #1/INFO]: UUID of player PsychoLynx is 68abdd33-8c33-4a6b-9aa2-9f1ba3e22b70
[14:31:58] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to RadarJammer v2.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:331) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:157) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:147) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:834) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_10_R1/entity/CraftPlayer
	at com.biggestnerd.radarjammer.VisibilityManager.getPing(VisibilityManager.java:462) ~[?:?]
	at com.biggestnerd.radarjammer.VisibilityManager.onPlayerJoin(VisibilityManager.java:268) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	... 14 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_92]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_92]
	at com.biggestnerd.radarjammer.VisibilityManager.getPing(VisibilityManager.java:462) ~[?:?]
	at com.biggestnerd.radarjammer.VisibilityManager.onPlayerJoin(VisibilityManager.java:268) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	... 14 more

**Comment by TealNerd** [comment]
Somehow the import change didnt get pushed with the updated pom, should be good now
