### ISSUE TITLE
Exception with Spigot 1.12

### ISSUE THREAD

**Issue by SlimeDog** [TealNerd/RadarJammer#9]
Spigot 1.12-pre2
RadarJammer 2.4

> [07:25:58] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to RadarJammer v2.4
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-743252d]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-743252d]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-743252d]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-743252d]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:342) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-743252d]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:162) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-743252d]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:147) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-743252d]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-743252d]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-743252d]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-743252d]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-743252d]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-743252d]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-743252d]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12-pre2.jar:git-Spigot-429b0e3-743252d]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_11_R1/entity/CraftPlayer
	at com.biggestnerd.radarjammer.VisibilityManager.getPing(VisibilityManager.java:462) ~[?:?]
	at com.biggestnerd.radarjammer.VisibilityManager.onPlayerJoin(VisibilityManager.java:268) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-743252d]
	... 14 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-743252d]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-743252d]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at com.biggestnerd.radarjammer.VisibilityManager.getPing(VisibilityManager.java:462) ~[?:?]
	at com.biggestnerd.radarjammer.VisibilityManager.onPlayerJoin(VisibilityManager.java:268) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12-pre2.jar:git-Spigot-429b0e3-743252d]
	... 14 more

**Comment by TealNerd** [comment]
Well duh, it's not updated for 1.12

**Comment by SlimeDog** [comment]
I'm very aware. The report was meant to offer encouragement to make it so, with a few hints on where to look for NPEs. :)

I would be happy to help test, when it's updated.
